name: Run Tests and Check Coverage

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Set the Python version you are using

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r rest_api/example/books_library/requirements.txt
        pip install coverage codecov
    
    - name: Set up Firebase credentials
      run: |
        echo "${{ secrets.FIREBASE_CREDENTIALS }}" | base64 --decode > rest_api/example/books_library/config/pse_2024_0809-cred.json

    # Step 4: Run unit tests and generate coverage report
    - name: Run tests with coverage
      run: |
        python -m coverage run -m unittest discover -s rest_api/example/books_library/tests
        python -m coverage report -m
        python -m coverage xml
        python -m coverage html

    # Step 5: Fail if coverage is less than 80%
    - name: Check coverage threshold
      run: |
        python -m coverage report --fail-under=80

    # Step 6: Upload HTML coverage report as artifact
    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v4
      with:
        name: html-coverage-report
        path: htmlcov

    # Step 7: Upload coverage report to Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        # The following token is not needed for public repositories, but is required for private ones.
        token: ${{ secrets.CODECOV_TOKEN }}

